# Site settings
title: Tai Wei's Blog
email: 18501232820@163.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  taivi

# Build settings
markdown: kramdown
